### ISSUE TITLE
How is this on PyPy?

### ISSUE THREAD

**Issue by v3ss0n** [squeaky-pl/japronto#22] opened 2017-02-02 10:20 UTC
Since it is written mostly in C , it won't work in pypy right ?

**Comment by squeaky-pl** [comment] 2017-02-02 10:32
Hi, I have PyPy on my radar, though I am not gonna look into it until PyPy reaches 3.5 compatibility somewhere later this year and most known JIT regressions are removed.

You are correct, it's tightly coupled to CPython's extension API at the moment. I made some pree liminary tests with cffi in the beginning but a lot of cffi calls in tight loop turned to be slower on CPython so I gave up. You can find parser bingings in src/parser that worked on PyPy but were slower. Said that I have some new ideas since then but I'm not going to invest time until PyPy 3.5 is done.

**Comment by v3ss0n** [comment] 2017-02-02 13:14
they are working on c-pyext for pypy , so it will be fine with CPython extension api (if it ever get stable).

Waiting for PyPy3.5 too.

**Comment by kawing-chiu** [comment] 2017-02-03 07:40
Looking forward to seeing a 10x speed bump on pypy :)

**Comment by squeaky-pl** [comment] 2017-02-04 04:37
Closing this in favor of 0b5fb17.

**Closed by squeaky-pl** 2017-02-04 04:37 UTC
