### ISSUE TITLE
SystemError: NULL result without error in PyObject_Call

### ISSUE THREAD

**Issue by kamilgregorczyk** [squeaky-pl/japronto#121] opened 2018-04-23 10:09 UTC
I tried to run it on debian & macOS with python 3.6,
 I'm getting such error on every request:
```
➜  ~ python3 test.py 
Accepting connections on http://0.0.0.0:8080
Exception in callback UVTransport._call_connection_made
handle: <Handle UVTransport._call_connection_made>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run
  File "uvloop/handles/tcp.pyx", line 149, in uvloop.loop.TCPTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 156, in uvloop.loop.UVBaseTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 153, in uvloop.loop.UVBaseTransport._call_connection_made
SystemError: NULL result without error in PyObject_Call
Exception in callback UVTransport._call_connection_made
handle: <Handle UVTransport._call_connection_made>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run
  File "uvloop/handles/tcp.pyx", line 149, in uvloop.loop.TCPTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 156, in uvloop.loop.UVBaseTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 153, in uvloop.loop.UVBaseTransport._call_connection_made
SystemError: NULL result without error in PyObject_Call

```

**Comment by squeaky-pl** [comment] 2018-04-23 11:39
Duplicate of https://github.com/squeaky-pl/japronto/issues/99

**Closed by squeaky-pl** 2018-04-23 11:39 UTC
